# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaplerSquad < Formula
  desc "Manage multiple AI terminal agents like Claude Code, Aider, Codex, OpenCode, and Amp."
  homepage "https://github.com/TylerStaplerAtFanatics/stapler-squad"
  version "1.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.7.3/stapler-squad_1.7.3_darwin_amd64.tar.gz"
      sha256 "1150c35a29378d734692c3df4e699114032b09347577a9df80d0500d83bb35af"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.7.3/stapler-squad_1.7.3_darwin_arm64.tar.gz"
      sha256 "09c2ce925b3be3342b40b7fc38d8d9f0ceaca7ba5f8576dbc40e11621ba22e74"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.7.3/stapler-squad_1.7.3_linux_amd64.tar.gz"
      sha256 "e447636ffb763647e501bc6ce7a80a72f806c29e4e58b149f555c7c956fd6fcf"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.7.3/stapler-squad_1.7.3_linux_arm64.tar.gz"
      sha256 "b4439c08755f634c89b9c67f041703968ec373f82f3a95e50dda11719d28811f"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  test do
    system "#{bin}/stapler-squad version"
  end
end
