# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaplerSquad < Formula
  desc "Manage multiple AI terminal agents like Claude Code, Aider, Codex, OpenCode, and Amp."
  homepage "https://github.com/TylerStaplerAtFanatics/stapler-squad"
  version "1.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.1/stapler-squad_1.8.1_darwin_amd64.tar.gz"
      sha256 "003d654c1a43652db09f1c84b8db2cfb4a61d66ac02b571d90e24e9d13f84781"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.1/stapler-squad_1.8.1_darwin_arm64.tar.gz"
      sha256 "396a169b56b408a380fdacfb5d0300949369eb165c15e13ce4a888921927faa2"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.1/stapler-squad_1.8.1_linux_amd64.tar.gz"
      sha256 "aa6c7991160aa2b185c2238fdb9ef506b36db71c19673043012399eeae6b5ff6"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.1/stapler-squad_1.8.1_linux_arm64.tar.gz"
      sha256 "4c539518ffcce408aca6177f51276176204f23ae682505ffb510058d3388e939"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  test do
    system "#{bin}/stapler-squad version"
  end
end
