# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaplerSquad < Formula
  desc "Manage multiple AI terminal agents like Claude Code, Aider, Codex, OpenCode, and Amp."
  homepage "https://github.com/TylerStaplerAtFanatics/stapler-squad"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.0/stapler-squad_1.8.0_darwin_amd64.tar.gz"
      sha256 "e928cd85b7732fef8750688758a5227edfa0a98c5c44b893451c71b368762bbd"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.0/stapler-squad_1.8.0_darwin_arm64.tar.gz"
      sha256 "d2c8847f03a8da0756e34a698b78e19c2fff792e72573e9ba31637e129f83cb9"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.0/stapler-squad_1.8.0_linux_amd64.tar.gz"
      sha256 "7ca72ad0f55eb57e2752a449f2bc154f15286e758ae99fd99df2ae6f374ce621"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.8.0/stapler-squad_1.8.0_linux_arm64.tar.gz"
      sha256 "19ce1f6564675263562837a91abe1fd48dcd2f585c8f12ca35af4fbf6e1d1d14"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  test do
    system "#{bin}/stapler-squad version"
  end
end
